name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Installing NPM
      run: env
    
    - name: Installing NPM
      run: npm install
      
    - name: Generate deployment package
      run: zip -r deploy.zip * -x "**node_modules**"

      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: AKIA43TWLHSFXXQDTCBC
        aws_secret_key: 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
        application_name: teste-guilherme
        environment_name: Testeguilherme-env
        region: us-west-1
        deployment_package: deploy.zip
        version_label: 1
        
        
    - name: Deployed!
      run: echo App deployed to ELB

